FROM liquibase/liquibase:4.28

# Optional: Copy your changelog folder into the container
# If you want to use volume mounts instead, you can skip this
COPY app/src/main/resources/db/changelog /liquibase/changelog
